### PR TITLE
Adding Task1 Task2 and text file into repo!

### PR DESCRIPTION
**Pull request by StandingMike**

### CODE REVIEW

**Comment by IAMDOKTOR** [comment]
I guess it should be better if we store our code in different directories.

Please, create your personal folder, move `Task1_Python_script.py`, `papa-what-is-a-neural-network-c5e5cc427c7.txt` and `task2.ipynb` into it and I'll agree to merge.

**Comment by tanvirsinghahuja** [comment]
@alex-andrero by different directories, do you mean different branches?

**Comment by tanvirsinghahuja** [comment]
@StandingMike your current pull request includes the older version of the READ.me where your name is not mentioned. Please correct me if I'm mistaken

**Comment by tanvirsinghahuja** [comment]
> @StandingMike your current pull request includes the older version of the READ.me where your name is not mentioned. Please correct me if I'm mistaken

Sorry please ignore my comment. You raised a pull request for all files excluding README.md one.

**Comment by tanvirsinghahuja** [comment]
> I guess it should be better if we store our code in different directories.
> 
> Please, create your personal folder, move `Task1_Python_script.py`, `papa-what-is-a-neural-network-c5e5cc427c7.txt` and `task2.ipynb` into it and I'll agree to merge.

Do I have to review Mike's code or we need to do it the task ourselves and then merge the branches?

**Comment by IAMDOKTOR** [comment]
> @alex-andrero by different directories, do you mean different branches?

No, just different folders.

It'd also be good if we pull the changes through pull requests, but we can leave just the main branch.

**Comment by IAMDOKTOR** [comment]
@tanvirsinghahuja when you finish your task, you need to create a pull request & add me, Mike, or both to the reviewers. After that, we enter github & if everything's ok with the project structure - we approve and you (or we) can merge

**Comment by IAMDOKTOR** [comment]
I think it's not our job to check the code :)

**Pull request merged**
